services:
  mongodb:
    restart: always
    hostname: mongodb
    image: mongo:4.4.6
    command: --replSet rs0
    volumes:
      - mongodb_data:/data/db
      - ./devenv/docker/mongo/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

    networks:
      - unbody

    ports:
      - '27017:27017'

  redis:
    restart: always
    hostname: redis
    image: redis
    ports:
      - '6379:6379'

  temporal:
    image: temporalio/admin-tools:1.27.1-tctl-1.18.2-cli-1.3.0
    entrypoint: ["/init.sh"]
    ports:
      - 7233:7233 # Server
      - 8233:8233 # UI
      - 60896:60896 # /metrics
    volumes:
      - ./devenv/docker/temporal/init.sh:/init.sh:ro
    networks:
      - unbody

  weaviate:
    build:
      dockerfile: ./devenv/docker/weaviate/Dockerfile
    image: weaviate:unbody
    restart: always
    ports:
      - 8080:8080
      - 50051:50051
    environment:
      - QUERY_DEFAULTS_LIMIT=25
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - CLUSTER_HOSTNAME=node1
      - ENABLE_MODULES=text2vec-huggingface
      - CLUSTER_GOSSIP_BIND_PORT=7100
      - ENABLE_MODULES=text2vec-huggingface,generative-unbody,img2vec-custom,reranker-custom,multi2vec-custom
    volumes:
      - weaviate_data:/var/lib/weaviate
    command: --host 0.0.0.0 --port 8080 --scheme http
    networks:
      - unbody
    extra_hosts:
      # allow weaviate to access services on host
      # via the host.docker.internal hostname
      - 'host.docker.internal:host-gateway'

  img2vec-neural:
    image: semitechnologies/img2vec-pytorch:resnet50
    ports:
      - 3456:8080
    networks:
        - unbody
    environment:
        ENABLE_CUDA: "0"

  file-server:
    image: python:3.9-slim
    ports:
      - "5555:5555"
    volumes:
      - ./devenv/docker/file-server/files:/app/files
    command: >
      sh -c "cd /app/files && mkdir -p public private && python -m http.server 5555"
    networks:
      - unbody

volumes:
  mongodb_data:
    driver: local
  weaviate_data:
    driver: local

networks:
  unbody:
    driver: bridge
